# Generated by Django 3.1.2 on 2022-01-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('concours', models.CharField(max_length=255)),
                ('etablissement', models.CharField(max_length=255)),
                ('salle', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
                ('date_exam', models.DateField()),
                ('date_envoi', models.DateTimeField()),
                ('go', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidat',
            },
        ),
    ]
