# Generated by Django 3.1.2 on 2022-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
