# Generated by Django 3.1.2 on 2022-01-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_auto_20220105_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status_code',
            field=models.CharField(default='Nothing', max_length=255),
        ),
    ]
