# Generated by Django 3.1.2 on 2022-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0004_auto_20220105_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
