# Generated by Django 3.1.2 on 2022-01-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0005_auto_20220105_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_envoi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
